name: workspace_root
description: flutter-app-template workspace root.
publish_to: none

environment:
  sdk: ^3.7.0

workspace:
  - packages/design_system
  - packages/foundation
  - packages/navigation
  - packages/networking
  - packages/persistence
  - packages/session

dev_dependencies:
  very_good_analysis: ^7.0.0
